content/usage/third-party-compilers.md
• Made it clearer that gulp-less just doesn't support LESS's source-maps, and mentioned/linked to gulp-sourcemaps.
» As of gulp-less 1.3.6, none of LESS's source-map options are supported (AFAICT from reading its docs).  The gulp-less-recommended avenue is to use gulp-sourcemaps for both inline and external source maps.
=> Updated gulp-less note on `sourceMap`s for gulp-less 1.3.6 (the current version)

templates/usage.hbs
There's a link in the docs on this page [usage](http://lesscss.org/usage/#using-less) that uses `<a href="{{resolve 'index'}}/#using-less">` within [usage.hbs](https://github.com/less/less-docs/blob/master/templates/usage.hbs#L11). That link should be rendering `http://lesscss.org/#using-less` but it's rendering `http://lesscss.org/index.html/#using-less`. Since it's rendering to `index.html` and it's not removing the `path.extname` I can assume that It's because it's not finding it in resolves `pages` loop. I'm not sure how to fix it with `hbs`. But this does the trick.
=> broken link to usage

content/usage/programmatic-usage.md
also see: https://github.com/less/less-docs/issues/282
also mention that you can not use sourcemaps in browser.
=> set the options on the render function

content/features/detached-rulesets.md
I added some articles ("a" and "the") throughout to make the descriptions a little clearer. It may be the case that they purposely weren't used (e.g. "iPhone" instead of "the iPhone"), but they seemed to belong.
=> Miscellaneous grammatical edits

content/usage/plugins.md
Imports the Less code for Ionic Framework before your custom Less code. Ionic is a beautiful, open source front-end SDK for developing hybrid mobile apps with HTML5.
=> add Ionic plugin

content/usage/command-line-usage.md
npm now uses caret version ranges by default when add dependencies to package.json
=> Change "tilde version range" to "caret version range"

content/features/detached-rulesets.md
Ensure naming convention is followed in the detached rulesets examples.
=> Ensure naming convention is followed

content/usage/frameworks-using-less.md
Added library https://github.com/segundofdez/normalize.less based on famous normalize.css as example in Mixin libraries
=> Added normalize.less as example in Mixin libraries documentation

content/home/using-less.md
Currently, &lt;version&gt; in the filenames in Rhino section is incorrectly parsed as an HTML tag and thus not displayed by the browser. Replacing < and > with &amp;lt; and &amp;gt; fixes the problem.
=> Fix <version> in using-less.md

content/home/using-less.md
I changed `lessc in.less > out.css` example to normal `lessc in.less out.css`. When  users (those not very familiar with console stuff) get to use the redirected variant, futher they are about to face multiple confusions/problems with error/warning messages and source-map files. So it's actually important to start the docs with the proper native `lessc src dst` command line example.
=> Remove redirection from the intro command line example, remove deprecated -x option

content/usage/editors-and-plugins.md
HTMLKit Tools is an IDE that natively support LESS
=> Added HTMLKit Tools

content/usage/guis-for-less.md
Noticed that Crunch had a broken image the other day, so here's a new one.
=> Update broken Crunch app image and description

content/usage/command-line-usage.md
The language explaining the `paths` option is a little ambiguous. I interpreted it as "less will look for the `@import` files at the locations provided to `include-path`". But after [viewing the source](https://github.com/less/less.js/blob/59c012c16a71eca2fd9f354b8db8fffaa5e14d6d/lib/less-node/file-manager.js#L38) I now realize less *first* looks for the file at the absolute path specified by the `@import` rule and it only looks in the `include-path` locations if it's not found at the absolute path.
This PR clarifies this in the docs.
=> Clarify paths option

content/usage/editors-and-plugins.md
Added my less compiler for komodo edit/IDE. Was missing the ability for compiling Less in komodo.
Updated an old Less compiler to work with the latest Less and komodo version.
=> Added my less compiler for Komodo Edit/IDE

content/features/mixins-as-functions.md
Line 3: Missing an article before 'variable'.  
ie: variable =>  'a variable'
=> Grammar edit in mixins-as-functions.md

content/usage/third-party-compilers.md
RECESS is "NO LONGER MAINTAINED [and] DOES NOT WORK WITH NEWER LESS VERSIONS", so it should probably no longer be listed under third party compilers.
(Quote from https://github.com/twitter/recess)
=> Remove unmaintained third party tool

content/usage/plugins.md
Hi,
I created a less-plugin that lets you convert `.scss` files to `.less` or import SASS files directly into your LESS files. Would you be so kind to link it in your docs?
Edi
=> Add sass2less as a less preprocessor plugin

content/usage/developing-less.md
Related to https://github.com/less/less.js/pull/2950 which suggests a way to avoid global Grunt installation (`npm install -g grunt-cli`).
In short, `npm run grunt -- [command_name]` is now can be used instead of `grunt [command_name]` when the developer doesn't have `grunt-cli` installed globally.
=> Clarify how to run Grunt in developing-less.md

content/tools/online-less-compilers.md
less2css.org - Ad-riddled domain-squatter
dopefly.com/less-converter - Cannot parse any input
lessphp.gpeasy.com/demo - Leads to no page with no input/output field
precess - 502
ILess - Can't be reached
=> Remove disfunct online compilers

content/usage/less-options.md
Based on the guidelines mentioned in the [README](https://github.com/less/less-docs), this PR cleans up use of lowercase "less" throughout the file content/usage/less-options.md, updating to uppercase "Less" where appropriate.
=> Clean up "Less" capitalization in less-options.md

content/features/detached-rulesets.md
Normally, CSS properties are written with `selector { prop: value }` syntax, *without* trailing semicolon.  When I made my first ruleset, this didn't occur to me.  And the errors didn't really help me either.. Took a few minutes to figure it out.
=> Clarify trailing semicolon - this tripped me up

content/tools/editors-and-plugins.md
I referred this issue, Because Notepad++ codes moved from sourceforge to github repo.
https://github.com/less/less.js/issues/3449
=> Revise Npp-Less-Salitrero Link

content/features/mixins-aliasing.md
On line 65, the example referenced `#library.colors` instead of `#library.rules` which would have been a more valid example of the parentheses requirement. Reviewed the other examples and concluded that all examples should use `colors` instead of `rules`.
=> fixed code examples in mixins-aliasing.md

content/features/mixins.md
Found a missing word or two, so I gave a quick copyediting pass over the entire file
=> Small grammar fixes in mixins.md

content/usage/less-options.md
Minor copy adjustment to the docs - I think the number four was intended (instead of for)
=> Update less-options.md doc (for -> four)

content/tools/preprocessors.md, content/tools/third-party-compilers.md
There didn't seem to be a good existing section for this, so I made a new one. Do I need to link it from anywhere? I didn't see `editors-and-plugins` referenced anywhere, so I was assuming it'd be included automatically
=> Add svelte-preprocess to Tools section

content/usage/less-options.md
I did a quick search for other "less" + adverb constructs and didn't find any.
=> Avoid confusing phrasing in math options

templates/_plugins/navigation.js
> https://docsearch.algolia.com/docs/tips#add-anchors-to-headings
> When using headings (as mentioned above), you should also try to add a custom anchor to each of them. Anchors are specified by HTML attributes (name or id) added to headers that allow browsers to directly scroll to the right position in the page. They're accessible by clicking a link with # followed by the anchor.
DocSearch will honor such anchors and automatically bring your users to the anchor closest to the search result they selected.
```diff
-      $(this).removeAttr('id').addClass('docs-heading');
+      $(this).addClass('docs-heading');
```
After Change:
=> feat: keep h* id attribute for algolia

content/tools/frameworks-using-less.md
Fomantic-UI took over active development of SUI in 2018 and since then made use of LESS features for dynamic compilation of many classes for colors or sizing, which SUI still has hardcoded.
=> feat(docs): added fomantic-ui to framework list
