less/less-docs

content/usage/using-less-in-the-browser.md
see: http://stackoverflow.com/questions/4210160/safely-parsing-a-json-string-with-unquoted-keys
=> json keys should be quoted

content/features/variables.md
suggestion to close: https://github.com/less/less-docs/issues/289
=> import statements

content/usage/plugins.md
should also close https://github.com/less/less.js/issues/2176
=> CSScomb plugin

content/features/import-directives.md
https://github.com/less/less-docs/issues/302
=> multiple keywords

content/usage/plugins.md
=> add two plugin

content/usage/frameworks-using-less.md
add ngBoilerplate, A sophisticated build management system using Less for web apps (formerly ng-boilerplate).
=> add ngBoilerplate

content/features-overview.md
=> Fixed nesting indentation for media query example

content/functions/color-operations.md
according https://github.com/less/less.js/issues/2504
I'm not sure, should i add an example with method = relative set for each function too?
=> Update documentation for optional relative percentages

content/home/using-less.md
=> enable CORS for external source

content/usage/plugins.md
Adds [less-plugin-lists](https://github.com/seven-phases-max/less-plugin-lists) plugin to the list of plugins.
=> Add less-plugin-lists plugin

styles/components/main-nav.less, templates/includes/nav-main.hbs
should also close https://github.com/less/less-docs/issues/199
=> Active items should not have a link

CONTRIBUTING.md, README.md, content/features-overview.md, content/features/extend.md, content/features/import-directives.md, content/features/mixin-guards.md, content/features/mixins-parametric.md, content/features/mixins.md, content/features/parent-selectors.md, content/features/variables.md, content/home/download-options.md, content/home/using-less.md, content/usage/browser-support.md, content/usage/command-line-usage.md, content/usage/developing-less.md, content/usage/editors-and-plugins.md, content/usage/plugins.md, content/usage/programmatic-usage.md, content/usage/third-party-compilers.md, content/usage/using-less-in-the-browser.md, content/usage/v2-upgrade.md
Re: https://github.com/less/less-docs/issues/346
=> Attempting to make headings all conform to the same style

content/usage/v2-upgrade.md
=> Use numbered list for "Clean CSS" section

content/features-overview.md
Added details to operations:
* what it does to colors,
* number conversions,
* example #362. 
Alpha is defined as undefined.
=> Arithmetic operations on colors

content/functions/color-operations.md
Added tint and shade. Close #229
=> Added tint and shade

.assemblerc.yml, templates/includes/nav-main.hbs
=> Added try it link into top banner.

content/usage/developing-less.md
Added a new video under the Videos section
=> Added a Video section

content/usage/frameworks-using-less.md
=> Add Ant Design to UI/Theme Frameworks

content/functions/color-definition.md
=> Fixes blockquote rendering for rgba and hsl functions

content/usage/frameworks-using-less.md
This adds Strapless to the list of frameworks using Less, and removes its predecessor 1pxdeep.
=> Added Strapless to featured frameworks, removed 1pxdeep

content/tools/frameworks-using-less.md
=> Add Petal and Tuesday to Frameworks using LESS

content/tools/frameworks-using-less.md
I would like to add my LESS mixin Library to mixin library list. Thank You.
=> Add LESS Style Library

content/tools/online-less-compilers.md
Hellow,
just adding a link to my Less WebCompiler, for everyone who wants to use own coding standards on the returning CSS Output.
=> Adding less.pytes.net WebCompiler

content/functions/logical-functions.md
=> Use correct version

templates/includes/head.hbs
REF: https://github.com/scottjehl/Respond/releases
=> update IE8 polyfills and HTTPS

.travis.yml
Fix CI, for example https://travis-ci.com/github/less/less-docs/builds/209694027
=> Update .travis.yml to fix CI

.assemblerc.yml
=> chore: update cdn example link

content/tools/editors-and-plugins.md
=> Update information about JetBrains IDE

README.md
=> chore: Remove the broken deps badge

content/features-overview.md
=> fix: add division example (#561)

.gitmodules
Remove submodule,  next pr will add `github actions` to auto deploy less official doc !
=> docs: remove submodule

README.md
=> chore: add test status badge

.gitignore
=> ci: ignore dest build folder

README.md, templates/includes/nav-main.hbs
=> feat: add about page nav

package-lock.json, package.json
Fix this security issue https://github.com/less/less-docs/security/dependabot/72
=> deps: bump grunt to 1.5.3

styles/bootstrap/navbar.less, styles/docs.css, templates/includes/head.hbs, templates/includes/javascripts.hbs, templates/includes/nav-main.hbs
| Desc | ScreentShot |
| :---: | ---- |
| Navbar UI | <img src="https://user-images.githubusercontent.com/14012511/172844115-5db294cd-daf2-4422-beae-475859ef2470.png" width="1000px" /> |
| SearchModal | <img src="https://user-images.githubusercontent.com/14012511/172844216-027e36a0-6de3-4d4a-82fe-a40125ca4a51.png" width="1000px" /> |
| Mobile | DropDown | FullScreen Modal |
| :---: | :---- | :---- |
| ScreenShot | <img src="https://user-images.githubusercontent.com/14012511/172844297-06d52df5-9a9e-4126-8e9d-b83c7a5bb7b3.png" width="350px" /> | <img src="https://user-images.githubusercontent.com/14012511/172844409-fd851e17-09a2-4765-aadd-c0f0ba29e530.png" width="350px" /> |
cc @matthew-dean
=> feat: add docsearch support

.assemblerc.yml, data/team.yml, templates/includes/head.hbs, templates/includes/javascripts.hbs, templates/includes/social-buttons.hbs
[cdn.jsdelivr.net](http://cdn.jsdelivr.net/) not work in china, so replace it with [fastly.jsdelivr.net](http://fastly.jsdelivr.net/). And also fix `https` releative issue.
=> fix: replace broken cdn and fix https issue

templates/includes/javascripts.hbs
Add [Google Analytics 4](https://support.google.com/analytics/answer/10089681?hl=en) support.
=> chore: add Google Analytics 4

.assemblerc.yml, templates/includes/docs-header.hbs
=> chore: add playground entry on homepage

data/translations.yml
Try to fix https://github.com/less/less.js/issues/3743
=> chore: update Iranian translation website url

.github/workflows/deploy.yml
=> ci: update deploy.yml
